version: 1.0.{build}
branches:
  only:
  - master
configuration: 
- Release
image: Visual Studio 2017
nuget:
  project_feed: true
before_build:
  - nuget restore ./KSharp/KSharp.sln
build:
  verbosity: minimal
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  
deploy:
  - provider: NuGet
    artifact: KSharp
    api_key:
      secure: qP7D/OZt68TRxqtCOopzclL4SVSDXpMlBiDxtJsksJgE3nPcFlSKIxRGzGNDR31h
      
artifacts:
  - path: '**/KSharp*.nupkg'
    name: KSharp