version: 1.0.{build}
branches:
  only:
  - master
configuration: 
- Release
image: Visual Studio 2017
nuget:
  project_feed: true
before_build:
  - nuget restore ./KSharp/KSharp.sln
build:
  verbosity: minimal
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true
  
  deploy:
  - provider: NuGet
    symbol_server: https://ci.appveyor.com/nuget/desana/api/v2/package
    api_key:
      secure: 073qnfxkit318qgybkun1rwe