version: 1.0.{build}
branches:
  only:
  - master
configuration: 
- Debug
- Release
image: Visual Studio 2017
before_build:
  - nuget restore ./KSharp/KSharp.sln
 nuget:
  project_feed: true
build:
  verbosity: minimal
  publish_wap: true
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  parallel: true